[theme]
# Primary accent color for interactive elements.
primaryColor = "#89CFF3"

# Background color for the main content area.
backgroundColor = "#F0F3FF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#00A9FF"

# Color used for almost all text.
textColor = "#27374D"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"